# specify kubernetes namespace
namespace: default 

# the nebula images
image:
  # the nebula-graphd images,change tag to use a different version.
  graphd:
    repository: vesoft/nebula-graphd
    tag: nightly
    pullPolicy: Always
  # the nebula-metad images,change tag to use a different version.
  metad: 
    repository: vesoft/nebula-metad
    tag: nightly 
    pullPolicy: Always
  # the nebula storaged images,change tag to use a different version.
  storaged:
    repository: vesoft/nebula-storaged
    tag: nightly
    pullPolicy: Always 

# set livenessProbe, kubelet will check nebula pod alive
livenessProbe:
  graphd:
    Enable: true
  metad:
    Enable: true 
  storaged:
    Enable: true 

## Optional resource requests and limits for the nebula container
resources: 
  graphd:
    limits:
      cpu: 4000m
      memory: 8192Mi
    requests:
      cpu: 4000m
      memory: 8192Mi

  metad:
    limits:
      cpu: 4000m
      memory: 8192Mi
    requests:
      cpu: 4000m
      memory: 8192Mi
  
  storaged:
    limits:
      cpu: 4000m
      memory: 16384Mi
    requests:
      cpu: 4000m
      memory: 16384Mi

replication:
  ## Number of nebula-storaged replicas
  storaged:
    replicas: 3
  ## Number of nebula-metad replicas
  metad: 
    replicas: 3
  ## Number of nebula-graphd replicas
  graphd: 
    replicas: 3

port:
  ## Service And Container Port Setting of Nebula-Graphd  
  graphd:
    serviceType: ClusterIP 
    thriftPort: 3699
    httpPort: 13000 
    http2Port: 13002 
  ## Service And Container Port Setting of Nebula-Storaged  
  storaged:
    serviceType: ClusterIP 
    thriftPort: 45500 
    raftPort: 45501 
    httpPort: 12000
    http2Port: 12002 
  ## Service And Container Port Setting of Nebula-Metad  
  metad:
    serviceType: ClusterIP 
    thriftPort: 44500 
    raftPort: 44501 
    httpPort: 11000
    http2Port: 11002

## Storage Setting of Nebula-Metad and Nebula-Storaged
storage:
  storageClass: fast-disks
  storaged:
    size: 20Gi 
  metad:
    size: 20Gi 

nodeSelector: {}

tolerations: []

affinity: {}
